using DbSourceMapper.Utility;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Shared;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace DbSourceMapper.Models;

internal sealed class ConstructorModel : ModelDeclaration, IEquatable<ConstructorModel>
{
	private ConstructorModel(string name, string @namespace, bool generateToString, bool isRecord, ImmutableArray<Field> fields)
		: base(name, @namespace, generateToString, isRecord, fields) { }

	public static ConstructorModel Create(in GeneratorAttributeSyntaxContext context, INamedTypeSymbol type, string @namespace, ModelOptions options)
	{
		SemanticModel semanticModel = context.SemanticModel;

		ParameterListSyntax paramList = (ParameterListSyntax)context.TargetNode
			.ChildNodes()
			.FirstOrDefault(static n => n is ParameterListSyntax);

		ImmutableArray<Field> @params = paramList
			.Parameters
			.Select(p => (IParameterSymbol)semanticModel.GetDeclaredSymbol(p)!)
			.Select(static p => new Field(
				p.Name,
				Constants.DefaultDbDataTypes.Contains(p.Type.Name) ? string.Intern(p.Type.Name) : p.Type.Name)
			)
			.ToImmutableArray();
		return new ConstructorModel(type.Name, @namespace, options.HasFlag(ModelOptions.GenerateToString), type.IsRecord, @params);
	}
	public bool Equals(ConstructorModel other) => DataEquals(other);

	public override void RegisterModelOutput(SourceProductionContext context)
	{
		StringBuilder builder = new();

		builder.AppendLine(
		$$"""
			// <auto-generated/>

			namespace {{_namespace}}
			{
				partial {{(_isRecord ? "record" : "class")}} {{_name}} : global::DbSourceMapper.IDbSourceModel<{{_name}}>
				{
					public static {{_name}} GetSingleModel(global::System.Data.Common.DbDataReader reader, ref int index) => new(
			""");

		foreach (Field param in _fields)
		{
			if (Constants.DefaultDbDataTypes.Contains(param.Type))
			{
				builder.AppendLine($"			reader.Get{param.Type}(index++),");
				continue;
			}
			builder.AppendLine($"			{param.Type}.GetSingleModel(reader, ref index),");
		}

		builder.Remove(builder.Length - 3, 1);
		builder.AppendLine(@"		);");

		if (_generateToString)
		{
			builder.AppendLine($$""""
						public override string ToString() =>
							$"""
				"""");
			foreach (Field param in _fields)
				builder.AppendLine($@"			{param.Name}: {{{param.Name}}}");
			builder.AppendLine("			\"\"\";");
		}

		builder.AppendLine("""
				}
			}
			""");

		context.AddSource(FileName, builder.ToString());
	}
}

