using Microsoft.CodeAnalysis;
using Shared;
using System;
using System.Collections.Immutable;
using System.Text;

namespace OrmGenerator.Models;

internal sealed class ConstructorModel(string name, string @namespace, bool generateToString, bool isRecord, ImmutableArray<Field> fields)
	: ModelDeclaration(name, @namespace, generateToString, isRecord, fields), IEquatable<ConstructorModel>
{
	public override bool Equals(ModelDeclaration other) => other is ConstructorModel d && Equals(d);
	public bool Equals(ConstructorModel other)
	{
		if (_name != other._name || _namespace != other._namespace || _fields.Length != other._fields.Length)
			return false;

		for (int i = 0; i < _fields.Length; i++)
			if (!_fields[i].Equals(other._fields[i]))
				return false;
		return true;
	}

	public override void RegisterModelOutput(SourceProductionContext context)
	{
		StringBuilder builder = new();

		builder.AppendLine(
		$$"""
			/// <auto-generated/>

			using System.Data.Common;
			using OrmGenerator;

			namespace {{_namespace}};
			partial {{(_isRecord ? "record" : "class")}} {{_name}} : IOrmModel<{{_name}}>
			{
				public static {{_name}} GetSingleModel(DbDataReader reader, ref int index) => new(
			""");

		foreach (Field param in _fields)
		{
			if (Constants.DbDataTypes.Contains(param.Type))
			{
				builder.AppendLine($"		reader.Get{param.Type}(index++),");
				continue;
			}
			builder.AppendLine($"		{param.Type}.GetSingleModel(reader, ref index),");
		}

		builder.Remove(builder.Length - 3, 1);
		builder.AppendLine(@"	);");

		if (_generateToString)
		{
			builder.AppendLine($$""""
						public override string ToString() =>
							$"""
					"""");
			foreach (Field param in _fields)
				builder.AppendLine($@"		{param.Name}: {{{param.Name}}}");
			builder.AppendLine("		\"\"\";");
		}
		builder.AppendLine("}");

		context.AddSource(FileName, builder.ToString());
	}
}

