using Microsoft.CodeAnalysis;
using Shared;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace DbSourceMapper.Models;

internal sealed class ConstructorModel(string name, string @namespace, bool generateToString, bool isRecord, ImmutableArray<Field> fields)
	: ModelDeclaration(name, @namespace, generateToString, isRecord, fields), IEquatable<ConstructorModel>
{
	public override bool Equals(ModelDeclaration other) => other is ConstructorModel d && Equals(d);
	public bool Equals(ConstructorModel other)
	{
		if (_name != other._name || _namespace != other._namespace)
			return false;

		if (!_fields.SequenceEqual(other._fields))
			return false;
		return true;
	}

	public override void RegisterModelOutput(SourceProductionContext context)
	{
		StringBuilder builder = new();

		builder.AppendLine(
		$$"""
			// <auto-generated/>

			namespace {{_namespace}}
			{
				partial {{(_isRecord ? "record" : "class")}} {{_name}} : global::DbSourceMapper.IOrmModel<{{_name}}>
				{
					public static {{_name}} GetSingleModel(global::System.Data.Common.DbDataReader reader, ref int index) => new(
			""");

		foreach (Field param in _fields)
		{
			if (Constants.DefaultDbDataTypes.Contains(param.Type))
			{
				builder.AppendLine($"			reader.Get{param.Type}(index++),");
				continue;
			}
			builder.AppendLine($"			{param.Type}.GetSingleModel(reader, ref index),");
		}

		builder.Remove(builder.Length - 3, 1);
		builder.AppendLine(@"		);");

		if (_generateToString)
		{
			builder.AppendLine($$""""
							public override string ToString() =>
								$"""
					"""");
			foreach (Field param in _fields)
				builder.AppendLine($@"			{param.Name}: {{{param.Name}}}");
			builder.AppendLine("			\"\"\";");
		}
		builder.AppendLine("	}");
		builder.AppendLine("}");

		context.AddSource(FileName, builder.ToString());
	}
}

