using OrmGenerator.Models.Property;
using OrmGenerator.Utility;
using System;
using System.Collections.Immutable;
using System.Text;

namespace OrmGenerator.Models;

internal sealed class NestableRecordModelDeclaration(string name, string @namespace, ImmutableArray<IProperty> parameters, bool generateToString) : ModelDeclaration(name, @namespace, generateToString), IEquatable<NestableRecordModelDeclaration>
{
	private readonly ImmutableArray<IProperty> _parameters = parameters;

	public override bool Equals(ModelDeclaration other) => other is RecordModelDeclaration d && Equals(d);
	public bool Equals(NestableRecordModelDeclaration other)
	{
		if (_name != other._name || _namespace != other._namespace || _parameters.Length != other._parameters.Length)
			return false;

		for (int i = 0; i < _parameters.Length; i++)
			if (!_parameters[i].Equals(other._parameters[i]))
				return false;
		return true;
	}

	public override string SourceCode
	{
		get
		{
			StringBuilder builder = new();

			builder.AppendLine(
			$$"""
			/// <auto-generated/>

			using System.Data.Common;
			using OrmGenerator;

			namespace {{_namespace}};
			partial record {{_name}} : IOrmModel<{{_name}}>
			{
				public static {{_name}} GetSingleModel(DbDataReader reader, ref int index) => new(
			""");

			foreach (IProperty prop in _parameters)
			{
				if (prop is CustomProperty c)
					builder.AppendLine($"		{c.Type}.GetSingleModel(reader, ref index),");
				else
				{
					StandardProperty s = (StandardProperty)prop;
					builder.AppendLine($@"		reader.Get{s.Type.CsString}(index++),");
				}
			}

			builder.AppendLine(@"	);");
			if (_generateToString)
			{
				builder.AppendLine($$""""
						public override string ToString() =>
							$"""
					"""");
				foreach (IProperty prop in _parameters)
					builder.AppendLine($@"		{prop.Name}: {{{prop.Name}}}");
				builder.AppendLine("		\"\"\";");
			}
			builder.AppendLine("}");

			return builder.ToString();
		}
	}
}

