using OrmGenerator.Models.Property;
using OrmGenerator.Utility;
using System;
using System.Collections.Immutable;
using System.Text;

namespace OrmGenerator.Models;

internal class NestableClassModelDeclaration(string name, string @namespace, ImmutableArray<IProperty> properties, bool generateToString) : ModelDeclaration(name, @namespace, generateToString), IEquatable<NestableClassModelDeclaration>
{
	public readonly ImmutableArray<IProperty> _properties = properties;

	public override bool Equals(ModelDeclaration other) => other is NestableClassModelDeclaration d && Equals(d);
	public bool Equals(NestableClassModelDeclaration other)
	{
		if (_name != other._name || _namespace != other._namespace || _properties.Length != other._properties.Length)
			return false;

		for (int i = 0; i < _properties.Length; i++)
			if (!_properties[i].Equals(other._properties[i]))
				return false;
		return true;
	}
	public override string SourceCode
	{
		get
		{
			StringBuilder builder = new();

			builder.AppendLine(
			$$"""
			/// <auto-generated/>

			using System.Data.Common;
			using OrmGenerator;

			namespace {{_namespace}};
			partial class {{_name}} : IOrmModel<{{_name}}>
			{
				public static {{_name}} GetSingleModel(DbDataReader reader, ref int index) => new()
				{
			""");

			foreach (IProperty prop in _properties)
			{
				if (prop is CustomProperty c)
					builder.AppendLine($"		{c.Name} = {c.Type}.GetSingleModel(reader, ref index),");
				else
				{
					StandardProperty s = (StandardProperty)prop;
					builder.AppendLine($@"		{s.Name} = reader.Get{s.Type.CsString}(index++),");
				}
			}

			builder.AppendLine(@"	};");
			if (_generateToString)
			{
				builder.AppendLine($$""""
						public override string ToString() =>
							$"""
					"""");
				foreach (IProperty prop in _properties)
					builder.AppendLine($@"		{prop.Name}: {{{prop.Name}}}");
				builder.AppendLine("		\"\"\";");
			}
			builder.AppendLine("}");

			return builder.ToString();
		}
	}
}
