using DbSourceMapper.Utility;
using Microsoft.CodeAnalysis;
using Shared;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace DbSourceMapper.Models;

internal class PropertyModel : ModelDeclaration
{
	private PropertyModel(string name, string @namespace, bool generateToString, bool isRecord, ImmutableArray<Field> fields)
		: base(name, @namespace, generateToString, isRecord, fields) { }

	internal static PropertyModel Create(INamedTypeSymbol type, string @namespace, ModelOptions options)
	{
		ImmutableArray<Field> props = type
			.GetMembers()
			.OfType<IPropertySymbol>()
			.Where(static p => p.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal && p.SetMethod is not null)
			.Select(static p => new Field(
				p.Name,
				Constants.DefaultDbDataTypes.Contains(p.Type.Name) ? string.Intern(p.Type.Name) : p.Type.Name)
			)
			.ToImmutableArray();
		return new(type.Name, @namespace, options.HasFlag(ModelOptions.GenerateToString), type.IsRecord, props);
	}
	public override bool Equals(ModelDeclaration other) => other is PropertyModel && DataEquals(other);

	public override void RegisterModelOutput(SourceProductionContext context)
	{
		StringBuilder builder = new();

		builder.AppendLine(
		$$"""
			// <auto-generated/>

			namespace {{_namespace}}
			{
				partial {{(_isRecord ? "record" : "class")}} {{_name}} : global::DbSourceMapper.IDbSourceModel<{{_name}}>
				{
					public static {{_name}} GetSingleModel(global::System.Data.Common.DbDataReader reader, ref int index) => new()
					{
			""");

		foreach (Field prop in _fields)
		{
			if (Constants.DefaultDbDataTypes.Contains(prop.Type))
			{
				builder.AppendLine($"			{prop.Name} = reader.Get{prop.Type}(index++),");
				continue;
			}
			builder.AppendLine($"			{prop.Name} = {prop.Type}.GetSingleModel(reader, ref index),");
		}


		builder.AppendLine(@"		};");
		if (_generateToString)
		{
			builder.AppendLine($$""""
						public override string ToString() =>
							$"""
					"""");
			foreach (Field prop in _fields)
				builder.AppendLine($@"			{prop.Name}: {{{prop.Name}}}");
			builder.AppendLine("			\"\"\";");
		}
		builder.AppendLine("""
				}
			}
			""");

		context.AddSource(FileName, builder.ToString());
	}
}
