using Microsoft.CodeAnalysis;
using Shared;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace OrmGenerator.Models;

internal class PropertyModel(string name, string @namespace, bool generateToString, bool isRecord, ImmutableArray<Field> fields)
	: ModelDeclaration(name, @namespace, generateToString, isRecord, fields), IEquatable<PropertyModel>
{
	public override bool Equals(ModelDeclaration other) => other is PropertyModel d && Equals(d);
	public bool Equals(PropertyModel other)
	{
		if (_name != other._name || _namespace != other._namespace)
			return false;

		if(!_fields.SequenceEqual(other._fields))
			return false;

		return true;
	}

	public override void RegisterModelOutput(SourceProductionContext context)
	{
		StringBuilder builder = new();

		builder.AppendLine(
		$$"""
			// <auto-generated/>

			namespace {{_namespace}}
			{
				partial {{(_isRecord ? "record" : "class")}} {{_name}} : global::OrmGenerator.IOrmModel<{{_name}}>
				{
					public static {{_name}} GetSingleModel(global::System.Data.Common.DbDataReader reader, ref int index) => new()
					{
			""");

		foreach (Field prop in _fields)
		{
			if (Constants.DefaultDbDataTypes.Contains(prop.Type))
			{
				builder.AppendLine($"			{prop.Name} = reader.Get{prop.Type}(index++),");
				continue;
			}
			builder.AppendLine($"			{prop.Name} = {prop.Type}.GetSingleModel(reader, ref index),");
		}


		builder.AppendLine(@"		};");
		if (_generateToString)
		{
			builder.AppendLine($$""""
							public override string ToString() =>
								$"""
					"""");
			foreach (Field prop in _fields)
				builder.AppendLine($@"			{prop.Name}: {{{prop.Name}}}");
			builder.AppendLine("			\"\"\";");
		}
		builder.AppendLine("	}");
		builder.AppendLine("}");

		context.AddSource(FileName, builder.ToString());
	}
}
