using OrmGenerator.Models.Field;
using Shared;
using System;
using System.Collections.Immutable;
using System.Text;

namespace OrmGenerator.Models;

internal sealed class PropertyModel(string name, string @namespace, ImmutableArray<NativeField> properties, bool generateToString) : ModelDeclaration(name, @namespace, generateToString), IEquatable<PropertyModel>
{
	private readonly ImmutableArray<NativeField> _properties = properties;

	public override bool Equals(ModelDeclaration other) => other is PropertyModel d && Equals(d);
	public bool Equals(PropertyModel other)
	{
		if (_name != other._name || _namespace != other._namespace || _properties.Length != other._properties.Length)
			return false;

		for (int i = 0; i < _properties.Length; i++)
			if (!_properties[i].Equals(other._properties[i]))
				return false;
		return true;
	}

	public override string SourceCode
	{
		get
		{
			StringBuilder builder = new();

			builder.AppendLine(
			$$"""
			/// <auto-generated/>
			
			using System.Data.Common;
			using OrmGenerator;

			namespace {{_namespace}};
			partial class {{_name}} : IOrmModel<{{_name}}>
			{
				public static {{_name}} GetSingleModel(DbDataReader reader, ref int index) => new()
				{
			""");

			foreach (NativeField prop in _properties)
				builder.AppendLine($@"		{prop.Name} = reader.Get{prop.Type.CsString}(index++),");


			builder.AppendLine(@"	};");
			if (_generateToString)
			{
				builder.AppendLine($$""""
						public override string ToString() =>
							$"""
					"""");
				foreach (NativeField prop in _properties)
					builder.AppendLine($"		{prop.Name}: {{{prop.Name}}}");
				builder.AppendLine("		\"\"\";");
			}
			builder.AppendLine("}");

			return builder.ToString();
		}
	}
}

