using OrmGenerator.Models.Property;
using OrmGenerator.Utility;
using System;
using System.Collections.Immutable;
using System.Text;

namespace OrmGenerator.Models;

internal sealed class RecordModelDeclaration(string name, string @namespace, ImmutableArray<StandardProperty> parameters, bool generateToString) : ModelDeclaration(name, @namespace, generateToString), IEquatable<RecordModelDeclaration>
{
	private readonly ImmutableArray<StandardProperty> _parameters = parameters;

	public override bool Equals(ModelDeclaration other) => other is RecordModelDeclaration d && Equals(d);
	public bool Equals(RecordModelDeclaration other)
	{
		if (_name != other._name || _namespace != other._namespace || _parameters.Length != other._parameters.Length)
			return false;

		for (int i = 0; i < _parameters.Length; i++)
			if (!_parameters[i].Equals(other._parameters[i]))
				return false;
		return true;
	}

	public override string SourceCode
	{
		get
		{
			StringBuilder builder = new();

			builder.AppendLine(
			$$"""
			/// <auto-generated/>
			
			using System.Data.Common;
			using OrmGenerator;

			namespace {{_namespace}};
			partial record {{_name}} : IOrmModel<{{_name}}>
			{
				public static {{_name}} GetSingleModel(DbDataReader reader, ref int index) => new(
			""");

			foreach (StandardProperty param in _parameters)
				builder.AppendLine($@"		reader.Get{param.Type.CsString}(index++),");


			builder.AppendLine(@"	);");
			if (_generateToString)
			{
				builder.AppendLine($$""""
						public override string ToString() =>
							$"""
					"""");
				foreach (StandardProperty param in _parameters)
					builder.AppendLine($"		{param.Name}: {{{param.Name}}}");
				builder.AppendLine("		\"\"\";");
			}
			builder.AppendLine("}");

			return builder.ToString();
		}
	}
}

