namespace OrmGenerator;

public sealed partial class MainGenerator
{
	private const string _baseMarker = "OrmGenerator.OrmModelAttribute";
	private const string _markerContent =
		"""
		/// <auto-generated/>
				
		using System;
		namespace OrmGenerator;

		[AttributeUsage(AttributeTargets.Class)]
		internal class OrmModelAttribute : Attribute
		{
			public bool GenerateToString { get; set; } = false;
		}

		internal sealed class NestableOrmModelAttribute : OrmModelAttribute;
		""";
	private const string _interfaceContent =
		"""
		/// <auto-generated/>
				
		using System.Data.Common;
		namespace OrmGenerator;

		/// <summary>
		/// Represents a model of type with source-generated mapping.
		/// This interface is used internally by the generator and it's not advised to use it elsewhere.
		/// </summary>
		public interface IOrmModel<TSelf> where TSelf : class
		{
					
			/// <summary>
			/// Initializes a new instance of the <see cref="TSelf"/> class.
			/// Provides a mechanism to handle nested models.
			/// This method is used internally by the generator and it's not advised to use it elsewhere.
			/// </summary>
			/// <typeparam name="TSelf">Model type returned from mapping</typeparam>
			internal static abstract TSelf GetSingleModel(DbDataReader reader, ref int index);
		}
		public static class ModelExtensions
		{
			extension<TModel>(TModel) where TModel: class, IOrmModel<TModel>
			{
				public static TModel GetSingleModel(DbDataReader reader)
				{
					int index = 0;
					return TModel.GetSingleModel(reader, ref index);
				}
			}
		}
		""";
	private const string _extensionsContent =
		"""
		/// <auto-generated/>
				
		#nullable enable

		using System.Data;
		using System.Data.Common;
		using System.Runtime.CompilerServices;
		namespace OrmGenerator;
				
		public static class DbCommandExtensions
		{
			private static TModel GetSingleModel<TModel>(DbDataReader reader) where TModel: class, IOrmModel<TModel>
			{
				int index = 0;
				return TModel.GetSingleModel(reader, ref index);
			}
		
			extension<TModel>(DbCommand command) where TModel: class, IOrmModel<TModel>
			{
				/// <summary>
				/// Executes the query defined in the <paramref name="command"/> parameter and maps the result to a single instance of <typeparamref name="TModel"/>.
				/// </summary>
				/// <param name="command"> The command to source data from.</param>
				/// <typeparam name="TModel"> Type of the model used as a result of mapping.</typeparam>
				/// <returns>A mapped <typeparamref name="TModel"/> instance or <c>null</c> if the query result is empty.</returns>
				public TModel? GetSingle()
				{
					using DbDataReader reader = command.ExecuteReader(CommandBehavior.SingleRow);
					return reader.Read() 
						? GetSingleModel<TModel>(reader) 
						: null;
				}

				/// <summary>
				/// Asynchronously executes the query defined in the <paramref name="command"/> parameter and maps the result to a single instance of <typeparamref name="TModel"/>.
				/// </summary>
				/// <param name="command"> The command to source data from.</param>
				/// <typeparam name="TModel"> Type of the model used as a result of mapping.</typeparam>
				/// <returns>A <see cref="Task{TModel}"/> containing a mapped <typeparamref name="TModel"/> instance or <c>null</c> if the query result is empty.</returns>
				public async Task<TModel?> GetSingleAsync(CancellationToken token = default)
				{
					using DbDataReader reader = await command.ExecuteReaderAsync(CommandBehavior.SingleRow, token);
					return await reader.ReadAsync(token) 
						? GetSingleModel<TModel>(reader) 
						: null;
				}

				/// <summary>
				/// Executes the query defined in the <paramref name="command"/> parameter, maps the results and returns them as a <see cref="List{}"/> of <typeparamref name="TModel"/>.
				/// </summary>
				/// <param name="command"> The command to source data from.</param>
				/// <typeparam name="TModel"> Type of the model used as a result of mapping.</typeparam>
				/// <returns>A <see cref="List{}" /> of mapped <typeparamref name="TModel"/>s.</returns>
				public List<TModel> GetListOf()
				{
					List<TModel> result = [];
					using DbDataReader reader = command.ExecuteReader();
				
					while(reader.Read())
						result.Add(GetSingleModel<TModel>(reader));
					return result;
				}

				/// <summary>
				/// Asynchronously executes the query defined in the <paramref name="command"/> parameter, maps the results and returns them as a <see cref="Task{}"/> of <see cref="List{}"/> of <typeparamref name="TModel"/>.
				/// </summary>
				/// <param name="command"> The command to source data from.</param>
				/// <typeparam name="TModel"> Type of the model used as a result of mapping.</typeparam>
				/// <returns>A <see cref="Task{TModel}"/> containing a <see cref="List{}" /> of mapped <typeparamref name="TModel"/>s.</returns>
				public async Task<List<TModel>> GetListOfAsync(CancellationToken token = default)
				{
					List<TModel> result = [];
					using DbDataReader reader = await command.ExecuteReaderAsync(token);
				
					while(await reader.ReadAsync(token))
						result.Add(GetSingleModel<TModel>(reader));
					return result;
				}

				/// <summary>
				/// Executes the query defined in the <paramref name="command"/> parameter, maps the results and returns them as a lazily evaluated <see cref="IEnumerable{}"/> of <typeparamref name="TModel"/>.
				/// </summary>
				/// <param name="command"> The command to source data from.</param>
				/// <typeparam name="TModel"> Type of the model used as a result of mapping.</typeparam>
				/// <returns>A lazily evaluated <see cref="IEnumerable{}"/> of mapped <typeparamref name="TModel"/>s.</returns>
				public IEnumerable<TModel> GetEnumerableOf()
				{
					using DbDataReader reader = command.ExecuteReader();
				
					while(reader.Read())
						yield return GetSingleModel<TModel>(reader);
				}

				/// <summary>
				/// Asynchronously executes the query defined in the <paramref name="command"/> parameter, maps the results and returns them as a lazily evaluated <see cref="IAsyncEnumerable{}"/> of <typeparamref name="TModel"/>.
				/// </summary>
				/// <param name="command"> The command to source data from.</param>
				/// <typeparam name="TModel"> Type of the model used as a result of mapping.</typeparam>
				/// <returns>A lazily evaluated <see cref="IAsyncEnumerable{}"/> of mapped <typeparamref name="TModel"/>s.</returns>
				public async IAsyncEnumerable<TModel> GetAsyncEnumerableOf([EnumeratorCancellation] CancellationToken token = default)
				{
					using DbDataReader reader = await command.ExecuteReaderAsync(token);
				
					while(await reader.ReadAsync(token))
						yield return GetSingleModel<TModel>(reader);
				}
			}
		}
		""";
}
