namespace DbSourceMapper;

public sealed partial class MainGenerator
{
	private const string _markerContent =
		//todo: xml docs for attribute parameters
		"""
		// <auto-generated/>

		#pragma warning disable CS9113 //Parameter read from semantics, false positive

		namespace DbSourceMapper
		{
			/// <summary>
			/// Used to mark models for database mapping generation.
			/// Requires the marked type to be defined as <c>partial</c> to work.
			/// </summary>

			[Microsoft.CodeAnalysis.Embedded]
			[global::System.AttributeUsage(global::System.AttributeTargets.Class)]
			internal sealed class DbSourceModelAttribute(global::DbSourceMapper.ModelOptions options = global::DbSourceMapper.ModelOptions.None) : global::System.Attribute {}

			/// <summary>
			/// Used to mark models for database mapping generation.
			/// Requires the marked type to be defined as <c>partial</c> to work.
			/// </summary>
		
			[Microsoft.CodeAnalysis.Embedded]
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
			internal sealed class DbSourceModelAttribute<TCommand>(global::DbSourceMapper.ModelOptions options = global::DbSourceMapper.ModelOptions.None) : global::System.Attribute where TCommand : global::System.Data.Common.DbCommand {}

			[global::System.Flags]
			internal enum ModelOptions
			{
				None = 0,
				/// <summary>
				/// Using this flag will make the generator use the type's primary constructor for mapping instead of all suitable properties.
				/// </summary>
				/// <remarks>
				/// Record types will always behave as if this flag was enabled.
				/// </remarks>
				UsePrimaryConstructor = 1 << 0,
				/// <summary>
				/// Determines whether the generator will emit a simple <c>ToString()</c> override for the model or not.
				/// </summary>
				GenerateToString = 1 << 1,
			}
		}
		#pragma warning restore CS9113
		""";
	private const string _interfaceContent =
		"""
		// <auto-generated/>
		#nullable enable

		namespace DbSourceMapper
		{
			/// <summary>
			/// Represents a model of type with source-generated mapping using a specific database provider.
			/// </summary>
			public interface IDbSourceModel<TSelf, TCommand> 
				where TSelf : class 
				where TCommand: global::System.Data.Common.DbCommand
			{
				public static abstract TSelf? GetFirstOrNull(TCommand command);
				public static abstract Task<TSelf?> GetFirstOrNullAsync(TCommand command, CancellationToken token);
				public static abstract List<TSelf> GetList(TCommand command);
				public static abstract Task<List<TSelf>> GetListAsync(TCommand command, CancellationToken token);
				public static abstract IEnumerable<TSelf> GetEnumerable(TCommand command);
				public static abstract IAsyncEnumerable<TSelf> GetAsyncEnumerable(TCommand command, CancellationToken token);
			}
		}
		""";
	private const string _extensionsContent =
		"""
		// <auto-generated/>
				
		#nullable enable

		namespace DbSourceMapper
		{
			public static class DbCommandExtensions
			{
				/// <summary>
				/// Executes the query defined in the <paramref name="command"/> parameter and maps the result to a single instance of <typeparamref name="TModel"/>.
				/// </summary>
				/// <param name="command"> The command to source data from.</param>
				/// <typeparam name="TModel"> Type of the model used as a result of mapping.</typeparam>
				/// <returns>A mapped <typeparamref name="TModel"/> instance or <c>null</c> if the query result is empty.</returns>
				public static TModel? GetFirstOrNull<TModel, TCommand>(this TCommand command) 
					where TCommand: global::System.Data.Common.DbCommand
					where TModel: class, global::DbSourceMapper.IDbSourceModel<TModel, TCommand>
					=> TModel.GetFirstOrNull(command);

		
				/// <summary>
				/// Asynchronously executes the query defined in the <paramref name="command"/> parameter and maps the result to a single instance of <typeparamref name="TModel"/>.
				/// </summary>
				/// <param name="command"> The command to source data from.</param>
				/// <typeparam name="TModel"> Type of the model used as a result of mapping.</typeparam>
				/// <returns>A <see cref="Task{TModel}"/> containing a mapped <typeparamref name="TModel"/> instance or <c>null</c> if the query result is empty.</returns>
				public static global::System.Threading.Tasks.Task<TModel?> GetFirstOrNullAsync<TModel, TCommand>(this TCommand command, global::System.Threading.CancellationToken token = default)
					where TCommand: global::System.Data.Common.DbCommand
					where TModel: class, global::DbSourceMapper.IDbSourceModel<TModel, TCommand>
					=> TModel.GetFirstOrNullAsync(command, token);
		
				/// <summary>
				/// Executes the query defined in the <paramref name="command"/> parameter, maps the results and returns them as a <see cref="List{}"/> of <typeparamref name="TModel"/>.
				/// </summary>
				/// <param name="command"> The command to source data from.</param>
				/// <typeparam name="TModel"> Type of the model used as a result of mapping.</typeparam>
				/// <returns>A <see cref="List{}" /> of mapped <typeparamref name="TModel"/>s.</returns>
				public static global::System.Collections.Generic.List<TModel> GetListOf<TModel, TCommand>(this TCommand command)
					where TCommand: global::System.Data.Common.DbCommand
					where TModel: class, global::DbSourceMapper.IDbSourceModel<TModel, TCommand>
					=> TModel.GetList(command);
		
				/// <summary>
				/// Asynchronously executes the query defined in the <paramref name="command"/> parameter, maps the results and returns them as a <see cref="Task{}"/> of <see cref="List{}"/> of <typeparamref name="TModel"/>.
				/// </summary>
				/// <param name="command"> The command to source data from.</param>
				/// <typeparam name="TModel"> Type of the model used as a result of mapping.</typeparam>
				/// <returns>A <see cref="Task{TModel}"/> containing a <see cref="List{}" /> of mapped <typeparamref name="TModel"/>s.</returns>
				public static global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<TModel>> GetListOfAsync<TModel,TCommand>(this TCommand command, global::System.Threading.CancellationToken token = default)
					where TCommand: global::System.Data.Common.DbCommand
					where TModel: class, global::DbSourceMapper.IDbSourceModel<TModel, TCommand>
					=> TModel.GetListAsync(command, token);
		
				/// <summary>
				/// Executes the query defined in the <paramref name="command"/> parameter, maps the results and returns them as a lazily evaluated <see cref="IEnumerable{}"/> of <typeparamref name="TModel"/>.
				/// </summary>
				/// <param name="command"> The command to source data from.</param>
				/// <typeparam name="TModel"> Type of the model used as a result of mapping.</typeparam>
				/// <returns>A lazily evaluated <see cref="IEnumerable{}"/> of mapped <typeparamref name="TModel"/>s.</returns>
				public static global::System.Collections.Generic.IEnumerable<TModel> GetEnumerableOf<TModel, TCommand>(this TCommand command)
					where TCommand: global::System.Data.Common.DbCommand
					where TModel: class, global::DbSourceMapper.IDbSourceModel<TModel, TCommand>
					=> TModel.GetEnumerable(command);
		
				/// <summary>
				/// Asynchronously executes the query defined in the <paramref name="command"/> parameter, maps the results and returns them as a lazily evaluated <see cref="IAsyncEnumerable{}"/> of <typeparamref name="TModel"/>.
				/// </summary>
				/// <param name="command"> The command to source data from.</param>
				/// <typeparam name="TModel"> Type of the model used as a result of mapping.</typeparam>
				/// <returns>A lazily evaluated <see cref="IAsyncEnumerable{}"/> of mapped <typeparamref name="TModel"/>s.</returns>
				public static global::System.Collections.Generic.IAsyncEnumerable<TModel> GetAsyncEnumerableOf<TModel, TCommand>(this TCommand command, global::System.Threading.CancellationToken token = default)
					where TCommand: global::System.Data.Common.DbCommand
					where TModel: class, global::DbSourceMapper.IDbSourceModel<TModel, TCommand>
					=> TModel.GetAsyncEnumerable(command, token);
			}
		}
		""";
}