using Microsoft.CodeAnalysis;
using OrmGenerator.Models;
using OrmGenerator.Utility;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace OrmGenerator;

[Generator]
public sealed partial class MainGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static ctx =>
		{
			ctx.AddSource("OrmModelAttribute.g.cs", _markerContent);
			ctx.AddSource("IOrmModel.g.cs", _interfaceContent);
			ctx.AddSource("DbCommandExtensions.g.cs", _extensionsContent);
		});

		IncrementalValuesProvider<MetadataModel> provider = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				_baseMarker,
				predicate: static (node, _) => true,
				transform: static (context, token) =>
				{
					INamedTypeSymbol @class = (INamedTypeSymbol)context.TargetSymbol;
					bool generateToString = GetToStringInfo(context);
					ImmutableArray<(string, DbDataType)> prop = @class
						.GetMembers()
						.OfType<IPropertySymbol>()
						.Where(static p => p.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal && p.SetMethod is not null)
						.Select(static p => Enum.TryParse(p.Type.Name, true, out DbDataType dataType)
								? (p.Name, dataType)
								: (p.Name, DbDataType.Unknown))
						.ToImmutableArray();
					return new MetadataModel(@class.Name, @class.ContainingNamespace.Name, prop, generateToString);
				}
			);
		context.RegisterSourceOutput(provider, static (spc, model) =>
		{
			StringBuilder builder = new();
			(string name,
			string @namespace,
			bool generateToString,
			ImmutableArray<(string Name, DbDataType Type)> properties) = model;

			builder.AppendLine(
			$$"""
			/// <auto-generated/>
			
			using System.Data.Common;
			using OrmGenerator;

			namespace {{@namespace}};
			partial class {{name}} : IOrmModel<{{name}}>
			{
				public static {{name}} GetSingleModel(DbDataReader reader, ref int index) => new()
				{
			""");

			foreach ((string, DbDataType) prop in properties)
			{
				(string Name, DbDataType Type) = prop;
				builder.AppendLine($"		{Name} = reader.Get{(Type == DbDataType.Single ? "Float" : Type.ToString())}(index++),");
			}

			builder.AppendLine($$"""
				};
				public static {{name}} GetSingleModel(DbDataReader reader)
				{
					int index = 0;
					return GetSingleModel(reader, ref index);
				}
			""");
			if (model.GenerateToString)
			{
				builder.AppendLine($$""""
						public override string ToString() =>
							$"""
					"""");
				foreach ((string Name, DbDataType) prop in properties)
					builder.AppendLine($"		{prop.Name}: {{{prop.Name}}}");
				builder.AppendLine("	\"\"\";");
			}
			builder.AppendLine("}");

			spc.AddSource($"{@namespace}.{name}.g.cs", builder.ToString());
		});

		IncrementalValuesProvider<NestableMetadataModel> nestableProvider = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				"OrmGenerator.NestableOrmModelAttribute",
				predicate: static (node, _) => true,
				transform: static (context, token) =>
				{
					INamedTypeSymbol @class = (INamedTypeSymbol)context.TargetSymbol;
					bool generateToString = GetToStringInfo(context);
					ImmutableArray<(string, DbDataType, string?)> prop = @class
						.GetMembers()
						.OfType<IPropertySymbol>()
						.Where(static p => p.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal && p.SetMethod is not null)
						.Select(static p => Enum.TryParse(p.Type.Name, true, out DbDataType type)
								? (p.Name, type, null)
								: (p.Name, DbDataType.Unknown, p.Type.Name)
						)
						.ToImmutableArray();
					return new NestableMetadataModel(@class.Name, @class.ContainingNamespace.Name, prop, generateToString);
				}
			);
		context.RegisterSourceOutput(nestableProvider, static (spc, model) =>
		{
			StringBuilder builder = new();
			(string name,
			string @namespace,
			bool generateToString,
			ImmutableArray<(string Name, DbDataType Type, string? CustomType)> properties) = model;

			builder.AppendLine(
			$$"""
			/// <auto-generated/>
			
			using System.Data.Common;
			using OrmGenerator;

			namespace {{@namespace}};
			partial class {{name}} : IOrmModel<{{name}}>
			{
				public static {{name}} GetSingleModel(DbDataReader reader, ref int index) => new()
				{
			""");

			foreach ((string, DbDataType, string?) prop in properties)
			{
				(string Name, DbDataType Type, string? CustomType) = prop;
				if (Type == DbDataType.Unknown)
					builder.AppendLine($"		{Name} = {CustomType}.GetSingleModel(reader, ref index),");
				else
					builder.AppendLine($"		{Name} = reader.Get{(Type == DbDataType.Single ? "Float" : Type.ToString())}(index++),");
			}

			builder.AppendLine($$"""
				};
				public static {{name}} GetSingleModel(DbDataReader reader)
				{
					int index = 0;
					return GetSingleModel(reader, ref index);
				}			
			""");
			if (model.GenerateToString)
			{
				builder.AppendLine($$""""
						public override string ToString() =>
							$"""
					"""");
				foreach ((string Name, DbDataType, string?) prop in properties)
					builder.AppendLine($"		{prop.Name}: {{{prop.Name}}}");
				builder.AppendLine("	\"\"\";");
			}
			builder.AppendLine("}");

			spc.AddSource($"{@namespace}.{name}.g.cs", builder.ToString());
		});
	}

	private static bool GetToStringInfo(in GeneratorAttributeSyntaxContext context) => (bool)(context
		.Attributes[0]
		.NamedArguments
		.FirstOrDefault()
		.Value
		.Value ?? false);
}
