using Microsoft.CodeAnalysis;
using OrmGenerator.Models;
using OrmGenerator.Utility;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace OrmGenerator;

[Generator]
public class MainGenerator : IIncrementalGenerator
{
	private const string _baseMarker = "OrmGenerator.OrmModelAttribute";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static ctx =>
		{
			ctx.AddSource("OrmModelAttribute.g.cs",
				"""
				/// <auto-generated/>
				
				using System;
				namespace OrmGenerator;

				[AttributeUsage(AttributeTargets.Class)]
				internal class OrmModelAttribute : Attribute
				{
					public bool GenerateToString { get; set; } = false;
				}

				internal sealed class NestableOrmModelAttribute : OrmModelAttribute;
				""");
			ctx.AddSource("IOrmModel.g.cs",
				"""
				/// <auto-generated/>
				
				using System.Data.Common;
				namespace OrmGenerator;

				/// <summary>
				/// Represents a model of type with source-generated mapping.
				/// This interface is used by the generator and it's not advised to use it elsewhere.
				/// </summary>
				public interface IOrmModel<TSelf> where TSelf : class
				{
					
					/// <summary>
					/// Initializes a new instance of the <see cref="{TSelf}"/> class.
					/// Provides a mechanism to handle nested models.
					/// This method is used by the generator and it's not advised to use it elsewhere.
					/// </summary>
					/// <typeparam name="TSelf">Model type returned from mapping</typeparam>
					internal static abstract TSelf GetSingleModel(DbDataReader reader);
				}
				""");

			ctx.AddSource("DbCommandExtensions.g.cs",
				"""
				/// <auto-generated/>
				
				#nullable enable

				using System.Data;
				using System.Data.Common;
				namespace OrmGenerator;
				
				public static class DbCommandExtensions
				{
					public static T? GetSingle<T>(this DbCommand command) where T: class, IOrmModel<T>
					{
						using DbDataReader reader = command.ExecuteReader(CommandBehavior.SingleRow);
						return reader.Read() 
							? T.GetSingleModel(reader) 
							: null;
					}

					public static async Task<T?> GetSingleAsync<T>(this DbCommand command, CancellationToken token = default) where T: class, IOrmModel<T>
					{
						using DbDataReader reader = await command.ExecuteReaderAsync(CommandBehavior.SingleRow, token);
						return await reader.ReadAsync(token) 
							? T.GetSingleModel(reader) 
							: null;
					}

					public static List<T> GetListOf<T>(this DbCommand command) where T: class, IOrmModel<T>
					{
						List<T> result = [];
						using DbDataReader reader = command.ExecuteReader();
				
						while(reader.Read())
							result.Add(T.GetSingleModel(reader));
						return result;
					}

					public static async Task<List<T>> GetListOfAsync<T>(this DbCommand command, CancellationToken token = default) where T: class, IOrmModel<T>
					{
						List<T> result = [];
						using DbDataReader reader = await command.ExecuteReaderAsync(token);
				
						while(await reader.ReadAsync(token))
							result.Add(T.GetSingleModel(reader));
						return result;
					}

					public static IEnumerable<T> GetEnumerableOf<T>(this DbCommand command) where T: class, IOrmModel<T>
					{
						using DbDataReader reader = command.ExecuteReader();
				
						while(reader.Read())
							yield return T.GetSingleModel(reader);
					}

					public static async IAsyncEnumerable<T> GetAsyncEnumerableOf<T>(this DbCommand command, [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken token = default) where T: class, IOrmModel<T>
					{
						using DbDataReader reader = await command.ExecuteReaderAsync(token);
				
						while(await reader.ReadAsync(token))
							yield return T.GetSingleModel(reader);
					}
				}
				""");
		});

		IncrementalValuesProvider<MetadataModel> provider = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				_baseMarker,
				predicate: static (node, _) => true,
				transform: static (context, token) =>
				{
					INamedTypeSymbol @class = (INamedTypeSymbol)context.TargetSymbol;
					bool generateToString = GetToStringInfo(context);
					ImmutableArray<(string, DbDataType)> prop = @class
						.GetMembers()
						.OfType<IPropertySymbol>()
						.Where(static p => p.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal && p.SetMethod is not null)
						.Select(static p => Enum.TryParse(p.Type.Name, true, out DbDataType dataType)
								? (p.Name, dataType)
								: (p.Name, DbDataType.Unknown))
						.ToImmutableArray();
					return new MetadataModel(@class.Name, @class.ContainingNamespace.Name, prop, generateToString);
				}
			);
		context.RegisterSourceOutput(provider, static (spc, model) =>
		{
			StringBuilder builder = new();
			(string name,
			string @namespace,
			bool generateToString,
			ImmutableArray<(string Name, DbDataType Type)> properties) = model;

			builder.AppendLine(
			$$"""
			/// <auto-generated/>
			
			using System.Data.Common;
			using OrmGenerator;

			namespace {{@namespace}};
			partial class {{name}} : IOrmModel<{{name}}>
			{
				public static {{name}} GetSingleModel(DbDataReader reader, ref int index) => new()
				{
			""");

			foreach ((string, DbDataType) prop in properties)
			{
				(string Name, DbDataType Type) = prop;
				builder.AppendLine($"		{Name} = reader.Get{(Type == DbDataType.Single ? "Float" : Type.ToString())}(index++),");
			}

			builder.AppendLine($$"""
				};
				public static {{name}} GetSingleModel(DbDataReader reader)
				{
					int index = 0;
					return GetSingleModel(reader, ref index);
				}
			""");
			if (model.GenerateToString)
			{
				builder.AppendLine($$""""
						public override string ToString() =>
							$"""
					"""");
				foreach ((string Name, DbDataType) prop in properties)
					builder.AppendLine($"		{prop.Name}: {{{prop.Name}}}");
				builder.AppendLine("	\"\"\";");
			}
			builder.AppendLine("}");

			spc.AddSource($"{@namespace}.{name}.g.cs", builder.ToString());
		});

		IncrementalValuesProvider<NestableMetadataModel> nestableProvider = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				"OrmGenerator.NestableOrmModelAttribute",
				predicate: static (node, _) => true,
				transform: static (context, token) =>
				{
					INamedTypeSymbol @class = (INamedTypeSymbol)context.TargetSymbol;
					bool generateToString = GetToStringInfo(context);
					ImmutableArray<(string, DbDataType, string?)> prop = @class
						.GetMembers()
						.OfType<IPropertySymbol>()
						.Where(static p => p.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal && p.SetMethod is not null)
						.Select(static p => Enum.TryParse(p.Type.Name, true, out DbDataType type)
								? (p.Name, type, null)
								: (p.Name, DbDataType.Unknown, p.Type.Name)
						)
						.ToImmutableArray();
					return new NestableMetadataModel(@class.Name, @class.ContainingNamespace.Name, prop, generateToString);
				}
			);
		context.RegisterSourceOutput(nestableProvider, static (spc, model) =>
		{
			StringBuilder builder = new();
			(string name,
			string @namespace,
			bool generateToString,
			ImmutableArray<(string Name, DbDataType Type, string? CustomType)> properties) = model;

			builder.AppendLine(
			$$"""
			/// <auto-generated/>
			
			using System.Data.Common;
			using OrmGenerator;

			namespace {{@namespace}};
			partial class {{name}} : IOrmModel<{{name}}>
			{
				public static {{name}} GetSingleModel(DbDataReader reader, ref int index) => new()
				{
			""");

			foreach ((string, DbDataType, string?) prop in properties)
			{
				(string Name, DbDataType Type, string? CustomType) = prop;
				if (Type == DbDataType.Unknown)
					builder.AppendLine($"		{Name} = {CustomType}.GetSingleModel(reader, ref index),");
				else
					builder.AppendLine($"		{Name} = reader.Get{(Type == DbDataType.Single ? "Float" : Type.ToString())}(index++),");
			}

			builder.AppendLine($$"""
				};
				public static {{name}} GetSingleModel(DbDataReader reader)
				{
					int index = 0;
					return GetSingleModel(reader, ref index);
				}			
			""");
			if (model.GenerateToString)
			{
				builder.AppendLine($$""""
						public override string ToString() =>
							$"""
					"""");
				foreach ((string Name, DbDataType, string?) prop in properties)
					builder.AppendLine($"		{prop.Name}: {{{prop.Name}}}");
				builder.AppendLine("	\"\"\";");
			}
			builder.AppendLine("}");

			spc.AddSource($"{@namespace}.{name}.g.cs", builder.ToString());
		});
	}

	private static bool GetToStringInfo(in GeneratorAttributeSyntaxContext context) => (bool)(context
		.Attributes[0]
		.NamedArguments
		.FirstOrDefault()
		.Value
		.Value ?? false);
}
