using DbSourceMapper.Utility;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace DbSourceMapper.Models.Generic;

internal sealed class GenericConstructorModel : GenericModelDeclaration
{
	private GenericConstructorModel(string name, string @namespace, bool generateToString, bool isRecord, ImmutableArray<Field> fields, ImmutableArray<GenericParamModel> genericParam)
		: base(name, @namespace, generateToString, isRecord, fields, genericParam) { }

	public static GenericConstructorModel Create(in GeneratorAttributeSyntaxContext context, INamedTypeSymbol type, string @namespace, ModelOptions options, ImmutableArray<GenericParamModel> genericParam)
	{
		SemanticModel semanticModel = context.SemanticModel;

		ParameterListSyntax paramList = (ParameterListSyntax)context.TargetNode
			.ChildNodes()
			.FirstOrDefault(static n => n is ParameterListSyntax);

		ImmutableArray<Field> @params = paramList
			.Parameters
			.Select(p => (IParameterSymbol)semanticModel.GetDeclaredSymbol(p)!)
			.Select(p => new Field(p.Name, p.Type.Name))
			.ToImmutableArray();
		return new GenericConstructorModel(type.Name, @namespace, options.HasFlag(ModelOptions.GenerateToString), type.IsRecord, @params, genericParam);
	}
	public override bool Equals(GenericModelDeclaration other) => other is GenericConstructorModel && DataEquals(other);

	public override void RegisterModelOutput(SourceProductionContext context)
	{
		StringBuilder builder = new();
		builder.AppendLine(
		$$"""
			// <auto-generated/>
			#nullable enable
			
			namespace {{_namespace}}
			{
				partial {{(_isRecord ? "record" : "class")}} {{_name}} : {{string.Join(",",_paramData.Select(p=>$"global::DbSourceMapper.IDbSourceModel<{_name}, global::{p.FullCommandName}>"))}}
				{
			""");

		foreach ((string fullCommandName, string fullReaderName, ImmutableDictionary<string, string> availableTypes) in _paramData)
		{
			builder.AppendLine($$"""
					private static {{_name}} GetSingleModel({{fullReaderName}} reader)
					{
						int index = 0;
						return {{_name}}.GetSingleModel(reader, ref index);
					}
					[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
					internal static {{_name}} GetSingleModel(global::{{fullReaderName}} reader, ref int index) => new(
			""");

			foreach (Field param in _fields)
			{
				if (availableTypes.TryGetValue(param.Type, out string? methodName))
				{
					builder.AppendLine($"			reader.{methodName}(index++),");
					continue;
				}
				builder.AppendLine($"			{param.Type}.GetSingleModel(reader, ref index),");
			}

			builder.Remove(builder.Length - 3, 1);
			builder.AppendLine($$"""
					);


					[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
					public static {{_name}}? GetFirstOrNull(global::{{fullCommandName}} command)
					{
						using global::{{fullReaderName}} reader = command.ExecuteReader(global::System.Data.CommandBehavior.SingleRow);
						return reader.Read() 
							? GetSingleModel(reader) 
							: null;
					}
			
					[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
					public static async global::System.Threading.Tasks.Task<{{_name}}?> GetFirstOrNullAsync(global::{{fullCommandName}} command, global::System.Threading.CancellationToken token)
					{
						using global::{{fullReaderName}} reader = await command.ExecuteReaderAsync(global::System.Data.CommandBehavior.SingleRow, token);
						return await reader.ReadAsync(token) 
							? GetSingleModel(reader) 
							: null;
					}
			
					[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
					public static global::System.Collections.Generic.List<{{_name}}> GetList(global::{{fullCommandName}} command)
					{
						global::System.Collections.Generic.List<{{_name}}> result = new();
						using global::{{fullReaderName}} reader = command.ExecuteReader();
					
						while(reader.Read())
							result.Add(GetSingleModel(reader));
						return result;
					}
			
					[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
					public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<{{_name}}>> GetListAsync(global::{{fullCommandName}} command, global::System.Threading.CancellationToken token)
					{
						global::System.Collections.Generic.List<{{_name}}> result = new();
						using global::{{fullReaderName}} reader = await command.ExecuteReaderAsync(token);
					
						while(await reader.ReadAsync(token))
							result.Add(GetSingleModel(reader));
						return result;
					}
			
					[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
					public static global::System.Collections.Generic.IEnumerable<{{_name}}> GetEnumerable(global::{{fullCommandName}} command)
					{
						using global::{{fullReaderName}} reader = command.ExecuteReader();
					
						while(reader.Read())
							yield return GetSingleModel(reader);
					}
			
					[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
					public static async global::System.Collections.Generic.IAsyncEnumerable<{{_name}}> GetAsyncEnumerable(global::{{fullCommandName}} command, [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken token)
					{
						using global::{{fullReaderName}} reader = await command.ExecuteReaderAsync(token);
					
						while(await reader.ReadAsync(token))
							yield return GetSingleModel(reader);
					}
			""");
		}

		if (_generateToString)
		{
			builder.AppendLine($$""""
						public override string ToString() =>
							$"""
				"""");
			foreach (Field param in _fields)
				builder.AppendLine($@"			{param.Name}: {{{param.Name}}}");
			builder.AppendLine("			\"\"\";");
		}

		builder.AppendLine("""
				}
			}
			""");

		context.AddSource(FileName, builder.ToString());
	}
}