using DbSourceMapper.Utility;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace DbSourceMapper.Models.Generic;

internal sealed class GenericConstructorModel : GenericModelDeclaration
{
	private GenericConstructorModel(string name, string @namespace, bool generateToString, bool isRecord, ImmutableArray<Field> fields, ImmutableHashSet<string> availableTypes, string readerFullName)
		: base(name, @namespace, generateToString, isRecord, fields, availableTypes, readerFullName) { }

	public static GenericConstructorModel Create(in GeneratorAttributeSyntaxContext context, INamedTypeSymbol type, string @namespace, ModelOptions options, ImmutableHashSet<string> availableTypes, string readerFullName)
	{
		SemanticModel semanticModel = context.SemanticModel;

		ParameterListSyntax paramList = (ParameterListSyntax)context.TargetNode
			.ChildNodes()
			.FirstOrDefault(static n => n is ParameterListSyntax);

		ImmutableArray<Field> @params = paramList
			.Parameters
			.Select(p => (IParameterSymbol)semanticModel.GetDeclaredSymbol(p)!)
			.Select(p => new Field(p.Name, p.Type.Name))
			.ToImmutableArray();
		return new GenericConstructorModel(type.Name, @namespace, options.HasFlag(ModelOptions.GenerateToString), type.IsRecord, @params, availableTypes, readerFullName);
	}
	public override bool Equals(GenericModelDeclaration other) => other is GenericConstructorModel && DataEquals(other);

	public override void RegisterModelOutput(SourceProductionContext context)
	{
		StringBuilder builder = new();

		//todo: actual support for custom dbreaders
		builder.AppendLine(
		$$"""
			// <auto-generated/>

			namespace {{_namespace}}
			{
				partial {{(_isRecord ? "record" : "class")}} {{_name}} : global::DbSourceMapper.IDbSourceModel<{{_name}}>
				{
					public static {{_name}} GetSingleModel(global::{{_readerFullName}}, ref int index) => new(
			""");

		foreach (Field param in _fields)
		{
			if (_availableTypes.Contains(param.Type))
			{
				builder.AppendLine($"			reader.Get{param.Type}(index++),");
				continue;
			}
			builder.AppendLine($"			{param.Type}.GetSingleModel(reader, ref index),");
		}

		builder.Remove(builder.Length - 3, 1);
		builder.AppendLine(@"		);");

		if (_generateToString)
		{
			builder.AppendLine($$""""
						public override string ToString() =>
							$"""
				"""");
			foreach (Field param in _fields)
				builder.AppendLine($@"			{param.Name}: {{{param.Name}}}");
			builder.AppendLine("			\"\"\";");
		}

		builder.AppendLine("""
				}
			}
			""");

		context.AddSource(FileName, builder.ToString());
	}
}

