using DbSourceMapper.Utility;
using Microsoft.CodeAnalysis;
using Shared;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace DbSourceMapper.Models.Generic;

internal class GenericPropertyModel : GenericModelDeclaration
{
	private GenericPropertyModel(string name, string @namespace, bool generateToString, bool isRecord, ImmutableArray<Field> fields, GenericParamModel genericParam)
		: base(name, @namespace, generateToString, isRecord, fields, genericParam) { }

	internal static GenericPropertyModel Create(INamedTypeSymbol type, string @namespace, ModelOptions options, GenericParamModel genericParam)
	{
		ImmutableArray<Field> props = type
			.GetMembers()
			.OfType<IPropertySymbol>()
			.Where(static p => p.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal && p.SetMethod is not null)
			.Select(static p => new Field(
				p.Name,
				Constants.DefaultDbDataTypes.Contains(p.Type.Name) ? string.Intern(p.Type.Name) : p.Type.Name)
			)
			.ToImmutableArray();
		return new(type.Name, @namespace, options.HasFlag(ModelOptions.GenerateToString), type.IsRecord, props, genericParam);
	}
	public override bool Equals(GenericModelDeclaration other) => other is GenericPropertyModel && DataEquals(other);

	public override void RegisterModelOutput(SourceProductionContext context)
	{
		StringBuilder builder = new();
		var (fullCommandName, fullReaderName, availableTypes) = _paramData;

		builder.AppendLine(
		$$"""
			// <auto-generated/>

			namespace {{_namespace}}
			{
				partial {{(_isRecord ? "record" : "class")}} {{_name}} : global::DbSourceMapper.IDbSourceModel<{{_name}}, global::{{fullCommandName}}>
				{
					private static {{_name}} GetSingleModel(global::{{fullReaderName}} reader, ref int index) => new()
					{
			""");

		foreach (Field prop in _fields)
		{
			if (availableTypes.Contains(prop.Type))
			{
				builder.AppendLine($"			{prop.Name} = reader.Get{prop.Type}(index++),");
				continue;
			}
			builder.AppendLine($"			{prop.Name} = {prop.Type}.GetSingleModel(reader, ref index),");
		}


		builder.AppendLine($$"""
					};

					private static {{_name}} GetSingleModel(global::{{fullReaderName}} reader)
					{
						int index = 0;
						return {{_name}}.GetSingleModel(reader, ref index);
					}

					public static {{_name}}? GetFirstOrNull(global::{{fullCommandName}} command)
					{
						using global::{{fullReaderName}} reader = command.ExecuteReader(global::System.Data.CommandBehavior.SingleRow);
						return reader.Read() 
							? GetSingleModel(reader) 
							: null;
					}
			
					public static async global::System.Threading.Tasks.Task<{{_name}}?> GetFirstOrNullAsync(global::{{fullCommandName}} command, global::System.Threading.CancellationToken token)
					{
						using global::{{fullReaderName}} reader = await command.ExecuteReaderAsync(global::System.Data.CommandBehavior.SingleRow, token);
						return await reader.ReadAsync(token) 
							? GetSingleModel(reader) 
							: null;
					}
			
					public static global::System.Collections.Generic.List<{{_name}}> GetList(global::{{fullCommandName}} command)
					{
						global::System.Collections.Generic.List<{{_name}}> result = new();
						using global::{{fullReaderName}} reader = command.ExecuteReader();
					
						while(reader.Read())
							result.Add(GetSingleModel(reader));
						return result;
					}
			
					public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<{{_name}}>> GetListAsync(global::{{fullCommandName}} command, global::System.Threading.CancellationToken token)
					{
						global::System.Collections.Generic.List<{{_name}}> result = new();
						using global::{{fullReaderName}} reader = await command.ExecuteReaderAsync(token);
					
						while(await reader.ReadAsync(token))
							result.Add(GetSingleModel(reader));
						return result;
					}
			
					public static global::System.Collections.Generic.IEnumerable<{{_name}}> GetEnumerable(global::{{fullCommandName}} command)
					{
						using global::{{fullReaderName}} reader = command.ExecuteReader();
					
						while(reader.Read())
							yield return GetSingleModel(reader);
					}
			
					public static async global::System.Collections.Generic.IAsyncEnumerable<{{_name}}> GetAsyncEnumerable(global::{{fullCommandName}} command, [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken token)
					{
						using global::{{fullReaderName}} reader = await command.ExecuteReaderAsync(token);
					
						while(await reader.ReadAsync(token))
							yield return GetSingleModel(reader);
					}
			""");
			

		if (_generateToString)
		{
			builder.AppendLine($$""""
						public override string ToString() =>
							$"""
					"""");
			foreach (Field prop in _fields)
				builder.AppendLine($@"			{prop.Name}: {{{prop.Name}}}");
			builder.AppendLine("			\"\"\";");
		}
		builder.AppendLine("""
				}
			}
			""");

		context.AddSource(FileName, builder.ToString());
	}
}